name: build and push
on: [push, pull_request]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    strategy:
      matrix:
        glue-version: [glue-2.0, glue-3.0]
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: setup docker buildx
        uses: docker/setup-buildx-action@v1
      - name: docker metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=${{ matrix.glue-version }}
      - name: build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: ${{ github.event.pull_request.merged == true }}
          tags: ${{ steps.meta.outputs.tags }}
          target: ${{ matrix.glue-version }}
          labels: ${{ steps.meta.outputs.labels }}
          # https://github.com/docker/build-push-action/blob/master/docs/advanced/cache.md#github-cache
          cache-from: type=gha
          cache-to: type=gha
